# Generated by Django 3.0.3 on 2020-02-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('imbd_id', models.CharField(max_length=15)),
                ('poster', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('imbd_id', models.CharField(max_length=15)),
                ('poster', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
