# Generated by Django 3.0.3 on 2020-02-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imbd_id',
            new_name='imdb_id',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='imbd_id',
            new_name='imdb_id',
        ),
    ]
